<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'City' => 'Cidade',
    'Country Code' => 'Código do País',
    'IP Address' => 'Endereço IP',
    'IP Position Details' => 'Detalhes do posicionamento IP',
    'IP fetch error' => 'Buscar erro',
    'Latitude' => 'Latitude',
    'Longitude' => 'Longitude',
    'No data found for IP address {ip}.' => 'Nenhuma informação encontrada para o endereço IP {ip}.',
    'AS' => 'AS',
    'Continent' => 'Continente',
    'Continent Code' => 'Código do Continente',
    'Country' => 'País',
    'Currency' => 'Moeda',
    'District' => 'Distrito',
    'Flag' => 'Bandeira',
    'ISP' => 'ISP',
    'Mobile Connnection' => 'Conexão movel',
    'No data found for the user\'s IP address.' => 'Nenhuma informação encontrada para o usuário',
    'Organization' => 'Organização',
    'Proxy' => 'Proxy',
    'Region' => 'Região',
    'Region Code' => 'Código da Região',
    'Reverse DNS' => 'DNS Reverso',
    'Time Zone' => 'Fuso horário',
    'Zip' => 'CEP',
];
