<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'City' => 'Stad',
    'Country Code' => 'Landcode',
    'Country Name' => 'Naam van het land',
    'Fetching location info...' => 'Ophalen locatie info...',
    'IP Address' => 'IP-adres',
    'IP Position Details' => 'IP positie details',
    'IP fetch error' => 'IP ophalen error',
    'Latitude' => 'Breedtegraad',
    'Longitude' => 'Lengtegraad',
    'Metro Code' => 'Metro code',
    'No data found for IP address {ip}.' => 'Geen data gevonden voor IP-adres {ip}.',
    'No data found for the user\'s IP address.' => 'Geen data gevonden voor het IP-adres van de gebruiker.',
    'Region Code' => 'Regiocode',
    'Region Name' => 'Regionaam',
    'Time Zone' => 'Tijdzone',
    'Zip Code' => 'Postcode',
];
