<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'City' => 'Ciudad',
    'Country Code' => 'Código de país',
    'IP Address' => 'Dirección IP',
    'IP Position Details' => 'Detalles de la posición IP',
    'IP fetch error' => 'Error obteniendo datos IP',
    'Latitude' => 'Latitud',
    'Longitude' => 'Longitud',
    'No data found for IP address {ip}.' => 'Sin datos para la IP {ip}',
    'No data found for the user\'s IP address.' => 'Sin dato para el usuario IP',
    'Region Code' => 'Código de región',
    'Time Zone' => 'Zona Horaria',
    'AS' => '',
    'Continent' => '',
    'Continent Code' => '',
    'Country' => '',
    'Currency' => '',
    'District' => '',
    'Flag' => '',
    'ISP' => '',
    'Mobile Connnection' => '',
    'Organization' => '',
    'Proxy' => '',
    'Region' => '',
    'Reverse DNS' => '',
    'Zip' => '',
];
