<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'City' => 'Місто',
    'Country Code' => 'Код Країни',
    'IP Address' => 'IP-адреса',
    'IP Position Details' => 'Деталі IP Позиціонування',
    'IP fetch error' => 'Помилка отримання IP',
    'Latitude' => 'Широта',
    'Longitude' => 'Довгота',
    'No data found for IP address {ip}.' => 'Немає даних для IP-адреси {ip}.',
    'No data found for the user\'s IP address.' => 'Немає даних для IP-адреси користувача.',
    'Region Code' => 'Код Регіону',
    'Time Zone' => 'Часовий пояс',
    'AS' => '',
    'Continent' => '',
    'Continent Code' => '',
    'Country' => '',
    'Currency' => '',
    'District' => '',
    'Flag' => '',
    'ISP' => '',
    'Mobile Connnection' => '',
    'Organization' => '',
    'Proxy' => '',
    'Region' => '',
    'Reverse DNS' => '',
    'Zip' => '',
];
