<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'City' => 'Cidade',
    'Country Code' => 'Código do País',
    'Country Name' => 'Nome do País',
    'Fetching location info...' => '',
    'IP Address' => 'Endereço IP',
    'IP Position Details' => 'Detalhes do posicionamento IP',
    'IP fetch error' => 'Buscar erro',
    'Latitude' => 'Latitude',
    'Longitude' => 'Longitude',
    'No Flag' => '',
    'No data found for IP address {ip}.' => 'Nenhum informação encontrada para o endereço IP {ip}.',
    'Revalidate IP info' => 'Revalidar informações do IP',
];
